In [3]:
import torchvision
import torch

In [5]:
entrypoints = torch.hub.list('pytorch/vision')
entrypoints

Using cache found in /home/morgen/.cache/torch/hub/pytorch_vision_main


['alexnet',
 'convnext_base',
 'convnext_large',
 'convnext_small',
 'convnext_tiny',
 'deeplabv3_mobilenet_v3_large',
 'deeplabv3_resnet101',
 'deeplabv3_resnet50',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'efficientnet_b0',
 'efficientnet_b1',
 'efficientnet_b2',
 'efficientnet_b3',
 'efficientnet_b4',
 'efficientnet_b5',
 'efficientnet_b6',
 'efficientnet_b7',
 'efficientnet_v2_l',
 'efficientnet_v2_m',
 'efficientnet_v2_s',
 'fcn_resnet101',
 'fcn_resnet50',
 'get_model_weights',
 'get_weight',
 'googlenet',
 'inception_v3',
 'lraspp_mobilenet_v3_large',
 'maxvit_t',
 'mc3_18',
 'mnasnet0_5',
 'mnasnet0_75',
 'mnasnet1_0',
 'mnasnet1_3',
 'mobilenet_v2',
 'mobilenet_v3_large',
 'mobilenet_v3_small',
 'mvit_v1_b',
 'mvit_v2_s',
 'r2plus1d_18',
 'r3d_18',
 'raft_large',
 'raft_small',
 'regnet_x_16gf',
 'regnet_x_1_6gf',
 'regnet_x_32gf',
 'regnet_x_3_2gf',
 'regnet_x_400mf',
 'regnet_x_800mf',
 'regnet_x_8gf',
 'regnet_y_128gf',
 'regnet_y_16gf',
 'regnet_y_1

In [6]:
# from a github repo
repo = 'pytorch/vision'
model = torch.hub.load(repo, 'resnet50', weights='ResNet50_Weights.IMAGENET1K_V1')

Using cache found in /home/morgen/.cache/torch/hub/pytorch_vision_main
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /home/morgen/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|██████████| 97.8M/97.8M [00:17<00:00, 5.70MB/s]


In [13]:
model = torch.hub.load(repo, 'resnet18', weights='ResNet18_Weights.IMAGENET1K_V1')

Using cache found in /home/morgen/.cache/torch/hub/pytorch_vision_main


In [14]:
list(model.children())
from torchvision.models.resnet

[Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False),
 BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
 ReLU(inplace=True),
 MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False),
 Sequential(
   (0): BasicBlock(
     (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
     (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (relu): ReLU(inplace=True)
     (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
     (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
   )
   (1): BasicBlock(
     (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
     (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (relu): ReLU(inplace=True)
     (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), pad

# 索引填充

In [9]:
import torch

In [10]:
import variable_gather

In [12]:
mask = torch.randn((1200, 1200)).unsqueeze(dim=0).cuda() > 0.7
mask

tensor([[[False, False, False,  ..., False,  True, False],
         [ True, False, False,  ..., False, False, False],
         [ True, False, False,  ..., False, False, False],
         ...,
         [False,  True, False,  ..., False,  True, False],
         [False, False, False,  ..., False, False, False],
         [False, False,  True,  ..., False,  True, False]]], device='cuda:0')

In [15]:
output = variable_gather.gather_index(mask, 880)
output[0].shape

torch.Size([1, 1200, 880])

In [5]:
mask.size()

torch.Size([1, 3, 3])

In [21]:
import torch
a = torch.tensor([[1.0, 3, 4]])
a = a / a.norm(p=2, dim=1, keepdim=True)

tensor(1.)

In [25]:
a = torch.rand((3,3))
a = a > 0.5

In [26]:
a

tensor([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [27]:
~a

tensor([[False,  True, False],
        [False, False, False],
        [False, False, False]])

In [28]:
line_modes = torch.zeros((1, 2))
lines = torch.rand((1, 3))
line_modes[0, :] = lines[0, [0, 2]] / lines[0, [1]]

In [42]:
a = torch.rand((2, 3, 4))
b = a.flatten(0, 1)

In [40]:
b.data_ptr()

161411520

In [39]:
a.data_ptr()

161411520

In [45]:
a = torch.zeros((3, 2))
a[[0, 2], :] = torch.eye(2)

In [48]:
a[None, :, 0].shape

torch.Size([1, 3])

In [50]:
a[:, 0].unsqueeze(0).shape

torch.Size([1, 3])

In [52]:
a.shape

torch.Size([3, 2])

In [53]:
c = [a, a]

In [54]:
c

[tensor([[1., 0.],
         [0., 0.],
         [0., 1.]]),
 tensor([[1., 0.],
         [0., 0.],
         [0., 1.]])]

In [55]:
d, d = c

In [56]:
d

tensor([[1., 0.],
        [0., 0.],
        [0., 1.]])